- name: Add Elasticsearch repository key
  shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

- name: Add Elasticsearch repository
  shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

- name: Update apt cache
  apt:
     update_cache: yes

- name: Install Elasticsearch
  apt:
     name: elasticsearch
     state: present
     update_cache: yes

- name: Start Elasticsearch service
  systemd:
     name: elasticsearch
     state: started
     enabled: yes

- name: copy elastichq script
  template:
     src: "elastichq"
     dest: /usr/local/bin/elastichq
     mode: 0755
     owner: root
     group: root

- name: copy elastichq script
  template:
     src: "elastichq.service"
     dest: /etc/systemd/system/elastichq.service
     mode: 0644
     owner: root
     group: root

- name: restart elastichq
  service:
     name: elastichq
     state: restarted
     enabled: true

- name: wait for elastichq to become ready
  wait_for:
     host: "{{ elastichq_bind_host }}"
     port: "{{ elastichq_port }}"
     state: started
     delay: 5
     connect_timeout: 15
     timeout: 300

